DROP TABLE IF EXISTS Pantry;
DROP TABLE IF EXISTS Rankings;
DROP TABLE IF EXISTS Recipe_Keywords;
DROP TABLE IF EXISTS Ingredients;

DROP TABLE IF EXISTS Recipes;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Items;